### ISSUE TITLE
Fedora To-Do list

### ISSUE THREAD

**Issue by junghans** [diehlpk/hpx_packaging#3]
Things we need to fix before ask for a Fedora Review:
- [x] Put example in a separate package
- [x] Prefix too generic executable name wtih `hpx_`
- [x] Re-enable the `%check` block
- [x] Add nompi version to package
- [ ] Run `fedora-review`

**Comment by diehlpk** [comment]
This [koji](https://koji.fedoraproject.org/koji/taskinfo?taskID=30690799) build has the openmpi-example and mpich-example.

**Comment by junghans** [comment]
Nice!

**Comment by junghans** [comment]
For the tests, is there a smaller test set than `make tests`?

**Comment by diehlpk** [comment]
Yes, one can specify a regular expression to ctest and only the test matching these are exectued, see [here](https://github.com/STEllAR-GROUP/hpx/blob/master/.circleci/config.yml#L202).

For the rpm package may `ctest -T test --no-compress-output --output-on-failure -R tests.unit`

should be sufficient or?

**Comment by junghans** [comment]
Yeah some kind of less memory intensive test suite would be great, let's start with `tests.units`, the `%check` block is still here: https://github.com/diehlpk/hpx_packaging/blob/master/Fedora/hpx.spec#L180

**Comment by diehlpk** [comment]
Yes, I will add it in the next build. Currently, I run a build with the nonmpi package and adding hpx_ to all of the executable. 

@junghans Could be great if you could have a look to https://github.com/diehlpk/hpx_packaging/blob/master/Fedora/hpx.spec#L166 and https://github.com/diehlpk/hpx_packaging/blob/master/Fedora/hpx.spec#L186 and let me know if there is a more elegant way to build the nonmpi package?

**Comment by junghans** [comment]
I am just cleaning up another spec and I had the same question, so I inspired myself in the `elpa` package, one can do something like:
```bash
%build
. /etc/profile.d/modules.sh
for mpi in '' mpich openmpi ; do
  test -n "${mpi}" && module load mpi/${mpi}-%{_arch}
  mkdir -p ${mpi:-serial}
  pushd ${mpi:-serial}
  %{cmake}  ..
  %make_build
  popd
  test -n "${mpi}" && module unload mpi/${mpi}-%{_arch}
done
```
and
```bash
%install
. /etc/profile.d/modules.sh
for mpi in '' mpich openmpi ; do
  test -n "${mpi}" && module load mpi/${mpi}-%{_arch}
  %make_install -C ${mpi:-serial}
  test -n "${mpi}" && module unload mpi/${mpi}-%{_arch}
done
```

**Comment by diehlpk** [comment]
Ok, put somehow, we would need to add these lines to the install target or?

```
sed -i '1s@env python@python2@' %{buildroot}/%{_bindir}/{hpx*.py,hpxcxx}  %{buildroot}%{_libdir}/cmake/HPX/templates/hpx{cxx,run.py}.in
chmod +x  %{buildroot}%{_libdir}/cmake/HPX/templates/hpx{cxx,run.py}.in
cd  %{buildroot}/%{_bindir} && rename '' hpx_ * && cd .. 
```

**Comment by junghans** [comment]
I guess you would need to do something like:
```bash
%install
. /etc/profile.d/modules.sh
for mpi in '' mpich openmpi ; do
  test -n "${mpi}" && module load mpi/${mpi}-%{_arch}
  %make_install -C ${mpi:-serial}
  sed -i '1s@env python@python2@' %{buildroot}/${MPI_BIN:-%{_bindir}}/{hpx*.py,hpxcxx}  %{buildroot}${MPI_LIB:-%{_libdir}}/cmake/HPX/templates/hpx{cxx,run.py}.in
  chmod +x  %{buildroot}${MPI_LIB:-%{_libdir}}/cmake/HPX/templates/hpx{cxx,run.py}.in
  push  %{buildroot}/${MPI_BIN:-%{_bindir}} && rename '' hpx_ * && popd
  test -n "${mpi}" && module unload mpi/${mpi}-%{_arch}
done

**Comment by junghans** [comment]
In general, you could do everything what you are doing in shell script.

**Comment by diehlpk** [comment]
This [build](https://koji.fedoraproject.org/koji/taskinfo?taskID=30700920) has the check for the unit tests enabled and fails with

`CMakeFiles/partitioned_vector_transform_binary_test_exe.dir/partitioned_vector_transform_binary.cpp.o -c /builddir/build/BUILD/hpx-1.2.0-rc1/tests/unit/parallel/segmented_algorithms/partitioned_vector_transform_binary.cpp virtual memory exhausted: Operation not permitted`

I assume that the unit tests have the issue with the virtual memory. So do we need to run tests according the fedora guidelines?

**Comment by diehlpk** [comment]
In this [build](https://koji.fedoraproject.org/koji/taskinfo?taskID=30700841) the nonmpi example package has issues in finding the executables 

```
Executing(%doc): /bin/sh -e /var/tmp/rpm-tmp.wj8l3o
error: File not found: /builddir/build/BUILDROOT/hpx-1.2.0-0.1.rc1.i386/usr/bin/*
```
and it seems that these [lines](https://github.com/diehlpk/hpx_packaging/blob/master/Fedora/hpx.spec#L230) 

```
%files examples
%doc README.rst
%license LICENSE_1_0.txt
%{_bindir}/* 
```
are not working, but I do not understand why. @junghans Could you please have a look?

**Comment by junghans** [comment]
> I assume that the unit tests have the issue with the virtual memory. So do we need to run tests according the fedora guidelines?

This just means koji ran out of memory, pick a smaller test set. I had problem with `partitioned_vector_transform_binary` on my laptop as well.

**Comment by diehlpk** [comment]
Ok, I think that maybe running the examples should be fine, because some major things are tested there too. Once we fixed the issue with the hpx-example package, I will run it again using a smaller test set. Once I found a working test set, I will add it to the open suse spec file too.

**Comment by junghans** [comment]
> In this [build](https://koji.fedoraproject.org/koji/taskinfo?taskID=30700841) the nonmpi example package has issues in finding the executables
> 
> ```
> Executing(%doc): /bin/sh -e /var/tmp/rpm-tmp.wj8l3o
> error: File not found: /builddir/build/BUILDROOT/hpx-1.2.0-0.1.rc1.i386/usr/bin/*
> ```
> and it seems that these [lines](https://github.com/diehlpk/hpx_packaging/blob/master/Fedora/hpx.spec#L230)
> 
> ```
> %files examples
> %doc README.rst
> %license LICENSE_1_0.txt
> %{_bindir}/* 
> ```
> are not working, but I do not understand why. @junghans Could you please have a look?

This just means there are no files in `%{_bindir}` i.e. `/usr/bin/` after install. Did you move the executable in the nompi package around, too?

**Comment by diehlpk** [comment]
```
%make_install -C serial 
sed -i '1s@env python@python2@' %{buildroot}/%{_bindir}/{hpx*.py,hpxcxx}  %{buildroot}%{_libdir}/cmake/HPX/templates/hpx{cxx,run.py}.in
chmod +x  %{buildroot}%{_libdir}/cmake/HPX/templates/hpx{cxx,run.py}.in
for f in  %{_bindir}/* ; do mv $(dirname $f)/$(basename $f) $(dirname $f)/hpx_$(basename $f) ; done
```

Ok, I was not aware that I need to copy them too


`mv %{buildroot}/%{_bindir}/* %{_bindir}/`

so this should copy them

```
%make_install -C serial 
mv %{buildroot}/%{_bindir}/* %{_bindir}/
sed -i '1s@env python@python2@' %{buildroot}/%{_bindir}/{hpx*.py,hpxcxx}  %{buildroot}%{_libdir}/cmake/HPX/templates/hpx{cxx,run.py}.in
chmod +x  %{buildroot}%{_libdir}/cmake/HPX/templates/hpx{cxx,run.py}.in
for f in  %{_bindir}/* ; do mv $(dirname $f)/$(basename $f) $(dirname $f)/hpx_$(basename $f) ; done
```

**Comment by junghans** [comment]
No you shouldn’t copy them %{_bindir} in the %files section is relative to %builddir already, I saw in the install phase of the log some stuff got installed in /usr/bin, but then it seems to get removed before the %files section.

**Comment by diehlpk** [comment]
```
-- Installing: /builddir/build/BUILDROOT/hpx-1.2.0-0.1.rc1.i386/usr/bin/hpx_runtime
-- Set runtime path of "/builddir/build/BUILDROOT/hpx-1.2.0-0.1.rc1.i386/usr/bin/hpx_runtime" to ""
```
It seems that the installation path for the nonmpi compilation is wrong. How can I fix this?

**Comment by junghans** [comment]
> ```
> -- Installing: /builddir/build/BUILDROOT/hpx-1.2.0-0.1.rc1.i386/usr/bin/hpx_runtime
> -- Set runtime path of "/builddir/build/BUILDROOT/hpx-1.2.0-0.1.rc1.i386/usr/bin/hpx_runtime" to ""
> ```
> It seems that the installation path for the nonmpi compilation is wrong. How can I fix this?

No fedora disables rpath in the install und `/builddir/build/BUILDROOT/hpx-1.2.0-0.1.rc1.i386/usr/bin/` is just `%{_builddir}/%{_bindir}`.

**Comment by junghans** [comment]
Ok, got it, you rename the files for serial, but then you move them to `$MPIBIN` in the mpi install.

Does hpx support `CMAKE_INSTALL_BINDIR`?

Also renaming `hpxcxx` to `hpx_hpxcxx` is maybe not necessary.

**Comment by diehlpk** [comment]
For mpi we do sth like 

`mv %{buildroot}/%{_bindir}/* %{buildroot}/${MPI_BIN}/`

can we not do the same for the serial and just copy the files to /usr/bin?

**Comment by diehlpk** [comment]
For the check, we just could add -j 1 or -j 2 to reduce the memory consumption, we have to do this on circleci too.

**Comment by junghans** [comment]
> For mpi we do sth like
> 
> `mv %{buildroot}/%{_bindir}/* %{buildroot}/${MPI_BIN}/`
> 
> can we not do the same for the serial and just copy the files to /usr/bin?

Yes, but the serial binaries are still in `%{_bindir}` when the mpi install happens and then we move _all_ binaries.

**Comment by junghans** [comment]
> For the check, we just could add -j 1 or -j 2 to reduce the memory consumption, we have to do this on circleci too.

Looking at https://github.com/diehlpk/hpx_packaging/blob/master/Fedora/hpx.spec#L213 it is already `make` without any `-j1`, but `-R` option means something different in `make` than `ctest`.

**Comment by junghans** [comment]
Also see #4 for some minor rework incl. some try to fix the move issue.

**Comment by diehlpk** [comment]
Thanks, I will try a koji build with #4

**Comment by junghans** [comment]
I didn't test it and just saw there is a
```
. /etc/profile.d/modules.sh
```
Missing before each `for` loop.

**Comment by diehlpk** [comment]
I will add it. Is the space between the dot and slash correct?

**Comment by junghans** [comment]
Yes, `.` means the same as `source`.

**Comment by diehlpk** [comment]
@junghans The latest commit in the branch fedora/29 compiles and produces following packages:

- hpx-1.2.0-0.1.rc1.i686.rpm                  
- hpx-debuginfo-1.2.0-0.1.rc1.i686.rpm                  
- hpx-debugsource-1.2.0-0.1.rc1.i686.rpm                  
- hpx-devel-1.2.0-0.1.rc1.i686.rpm                  
- hpx-examples-1.2.0-0.1.rc1.i686.rpm                 
- hpx-examples-debuginfo-1.2.0-0.1.rc1.i686.rpm
- hpx-mpich-1.2.0-0.1.rc1.i686.rpm                 
- hpx-mpich-debuginfo-1.2.0-0.1.rc1.i686.rpm                 
- hpx-mpich-devel-1.2.0-0.1.rc1.i686.rpm                
- hpx-mpich-examples-1.2.0-0.1.rc1.i686.rpm                 
- hpx-mpich-examples-debuginfo-1.2.0-0.1.rc1.i686.rpm                 
- hpx-openmpi-1.2.0-0.1.rc1.i686.rpm                  
- hpx-openmpi-debuginfo-1.2.0-0.1.rc1.i686.rpm                  
- hpx-openmpi-devel-1.2.0-0.1.rc1.i686.rpm                  
- hpx-openmpi-examples-1.2.0-0.1.rc1.i686.rpm                  
- hpx-openmpi-examples-debuginfo-1.2.0-0.1.rc1.i686.rpm`

on [koji](https://koji.fedoraproject.org/koji/tasks?owner=diehlpk&state=all).

**Comment by diehlpk** [comment]
@junghans What would be the next step for the fedora-review?

**Comment by junghans** [comment]
Running the `fedora-review` tool before opening the review bug is always good!

**Comment by junghans** [comment]
What is the `${s:-.}` for?

**Comment by diehlpk** [comment]
Ok, I will run the fedora-review and update the spec file accordingly this evening. I fixed some issues in your pr, like mpi libs were not installed correctly, because the module was unloaded too early. I looked at the epal package and adapted most of these instructions and merged your pr to it.

Major changes are:
- having the examples in a package for each build
- having a devel package
- adding the examples to the check, since the hpx release candidate is tested

**Comment by diehlpk** [comment]
Started a rawhide [build](https://koji.fedoraproject.org/koji/taskinfo?taskID=30786022), since `fedora-review` should be run with it.

**Comment by junghans** [comment]
The ppc64le build fails with:
```
make[2]: *** Deleting file 'src/components/containers/partitioned_vector/CMakeFiles/partitioned_vector_component.dir/partitioned_vector_component_int.cpp.o'
make[2]: Entering directory '/builddir/build/BUILD/hpx-1.2.0-rc1/openmpi'
[ 42%] Building CXX object src/components/containers/partitioned_vector/CMakeFiles/partitioned_vector_component.dir/partitioned_vector_component_int.cpp.o
cd /builddir/build/BUILD/hpx-1.2.0-rc1/openmpi/src/components/containers/partitioned_vector && /usr/lib64/openmpi/bin/mpicxx  -DBOOST_DISABLE_ASSERTS -DHPX_COMPONENT_EXPORTS -DHPX_COMPONENT_NAME=hpx_partitioned_vector -DHPX_COMPONENT_STRING=\"hpx_partitioned_vector\" -DHPX_DISABLE_ASSERTS -DHPX_PARTITIONED_VECTOR_MODULE_EXPORTS -D_GNU_SOURCE -Dpartitioned_vector_component_EXPORTS -I/builddir/build/BUILD/hpx-1.2.0-rc1 -I/builddir/build/BUILD/hpx-1.2.0-rc1/openmpi  -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mcpu=power8 -mtune=power8 -fasynchronous-unwind-tables -fstack-clash-protection -DNDEBUG -fPIC   -std=c++17 -o CMakeFiles/partitioned_vector_component.dir/partitioned_vector_component_int.cpp.o -c /builddir/build/BUILD/hpx-1.2.0-rc1/src/components/containers/partitioned_vector/partitioned_vector_component_int.cpp
make[2]: Leaving directory '/builddir/build/BUILD/hpx-1.2.0-rc1/openmpi'
/builddir/build/BUILD/hpx-1.2.0-rc1/src/components/containers/partitioned_vector/partitioned_vector_component_int.cpp:27:18: warning: type attributes ignored after type is already defined [-Wattributes]
     hpx::server::partitioned_vector<int, std::vector<int>>;
                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/builddir/build/BUILD/hpx-1.2.0-rc1/src/components/containers/partitioned_vector/partitioned_vector_component_int.cpp:41:18: warning: type attributes ignored after type is already defined [-Wattributes]
     hpx::server::partitioned_vector<long long, std::vector<long long>>;
                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
{standard input}: Assembler messages:
{standard input}:14727476: Warning: end of file not at end of a line; newline inserted
g++: fatal error: Killed signal terminated program cc1plus
compilation terminated.
```

**Comment by junghans** [comment]
On x86_64 there are a lot of these`explicitly decompress any DWARF compressed ELF sections` warnings.

**Comment by diehlpk** [comment]
Ok, I will have a look into these ones after SC. Could we run fedora-review with the build for 29 or is rawhide mandatory? 

What would be the best way to get hpx into fedora 29 and deal with the rawhide issues later?

**Comment by junghans** [comment]
The review is usually done on rawhide (the master branch) and then merge downwards to f29 etc.

**Comment by junghans** [comment]
Maybe the best is just to execlude ppc64le for now.

**Comment by diehlpk** [comment]
Ok, I will do this and run a new build. Later after SC I will look into the arm and ppc64le build.

**Comment by diehlpk** [comment]
Is there any elegant way to reduce the number of cores for the build

`+ /usr/bin/make -O -j4`

I like to reduce the number of cores for the  ppc64le build

```
%ifarch ppc64le
%_smp_mflags  -j 2
%endif
```

**Comment by diehlpk** [comment]
So the build error was related to using too much cpu/memory and adding the code above [builds](https://koji.fedoraproject.org/koji/taskinfo?taskID=30789431)

**Comment by junghans** [comment]
> Is there any elegant way to reduce the number of cores for the build
> 
> `+ /usr/bin/make -O -j4`
> 
> I like to reduce the number of cores for the ppc64le build
> 
> ```
> %ifarch ppc64le
> %_smp_mflags  -j 2
> %endif
> ```
Overwritting `_smp_mflags` should be fine.

**Comment by junghans** [comment]
Can you checkin the latest version of the spec?

**Comment by diehlpk** [comment]
I will head to Dallas for SC 18 and will be offline for a while. Are you going to SC too?

**Comment by junghans** [comment]
> I will head to Dallas for SC 18 and will be offline for a while. Are you going to SC too?

No, I will not go this year.

**Comment by diehlpk** [comment]
Unfortunately, I am not able to run the fedora-review on my laptop, it crashes due to not having enough space on my disk.

**Comment by diehlpk** [comment]
https://koji.fedoraproject.org/koji/taskinfo?taskID=30904002

This seems that we should reduce the number of cpus for the aarch64 build as well. I could do it later today.

**Comment by junghans** [comment]
> This seems that we should reduce the number of cpus for the aarch64 build as well. I could do it later today.

#12

**Comment by diehlpk** [comment]
@junghans I think this issue can be closed or?

**Comment by junghans** [comment]
Yup
